apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          volumeMounts:
            - mountPath: /var/lib/rabbitmq/data
              name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pv-claim-openvidu
