apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuschecker
spec:
  selector:
    matchLabels:
      app: statuschecker
  replicas: 1
  template:
    metadata:
      labels:
        app: statuschecker
    spec:
      containers:
      - name: statuschecker
        image: nkrokhmal/statuschecker
        env:
        - name: CHUNK_TIME
          value: "360"        
        envFrom:
        - configMapRef:
            name: postgres
        imagePullPolicy: "Always"
        ports:
        - containerPort: 55558
      imagePullSecrets:
      - name: regcred
          
